name = "Mojolicious-Plugin-Inertia"
badges = ["github-actions/test.yml", "metacpan"]
module_maker="ModuleBuildTiny"
static_install = "auto"
authority = "cpan:KFLY"
markdown_maker = "Pod::Markdown::Github"

[release]
branch = "main"
